import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import React from "react";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import WaButton from "@/components/wa-button";

export const metadata: Metadata = {
  title: "Nabila Catering",
  description: "Generated by create next app",
};

const fonts = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="scroll-smooth">
    <body className={`${fonts.className} bg-white bg-dot-black/[0.2] overflow-x-hidden`}>
      <Navbar />
      {children}
      <WaButton />
      <Footer />
    </body>
    </html>
  );
}
