import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";

const fonts = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nabila Catering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${fonts.className}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
